# You can override default values of the properties by setting environment variables
spring:
  datasource:
    # SPRING_DATASOURCE_URL
    url: jdbc:postgresql://localhost:5432/jira
    # SPRING_DATASOURCE_USERNAME
    username: jira
    # SPRING_DATASOURCE_PASSWORD
    password: JiraRush
