# You can override default values of the properties by setting environment variables
spring:
  mail:
    # SPRING_MAIL_HOST
    host: smtp.gmail.com
    # SPRING_MAIL_USERNAME
    username: jira4jr@gmail.com
    # SPRING_MAIL_PASSWORD
    password: zdfzsrqvgimldzyj
    # SPRING_MAIL_POST
    port: 587
