# You can override default values of the properties by setting environment variables
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            # https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTID
            client-id: 3d0d8738e65881fff266
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENTSECRET
            client-secret: 0f97031ce6178b7dfb67a6af587f37e222a16120
          google:
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTID
            client-id: 329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENTSECRET
            client-secret: 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
          gitlab:
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITLAB_CLIENTID
            client-id: b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494
            # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITLAB_CLIENTSECRET
            client-secret: e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004
